# Config

# Packages needed


library(readxl)
library(phyloseq)
library(vegan)
library(tidyverse)
library(microbiome)
library(MetBrewer)
library(showtext)
library(microbiomeutilities)
library(ade4)
library(CCA)
library(correlation)
library(eulerr)
library(ggpubr)
library(ggsci)
library(gt)
library(gtable)
library(gtExtras)
library(patchwork)
library(qiime2R)
library(gtsummary)
library(ggfortify)
library(ANCOMBC)
library(MoMAColors)
library(pheatmap)
library(microeco)
library(file2meco)
library(vcfR)
library(adegenet)
library(reshape2)
library(microViz)
library(microbiomeMarker)
